(cl:defpackage ocrtoc_task-msg
  (:use )
  (:export
   "<CLEANACTION>"
   "CLEANACTION"
   "<CLEANACTIONFEEDBACK>"
   "CLEANACTIONFEEDBACK"
   "<CLEANACTIONGOAL>"
   "CLEANACTIONGOAL"
   "<CLEANACTIONRESULT>"
   "CLEANACTIONRESULT"
   "<CLEANFEEDBACK>"
   "CLEANFEEDBACK"
   "<CLEANGOAL>"
   "CLEANGOAL"
   "<CLEANRESULT>"
   "CLEANRESULT"
  ))

