arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_1_s 
     - joint_2_l
     - joint_3_u
     - joint_4_r
     - joint_5_b 
     - joint_6_t
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - claw_1b_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
