// Generated by gencpp from file ocrtoc_task/CleanResult.msg
// DO NOT EDIT!


#ifndef OCRTOC_TASK_MESSAGE_CLEANRESULT_H
#define OCRTOC_TASK_MESSAGE_CLEANRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ocrtoc_task
{
template <class ContainerAllocator>
struct CleanResult_
{
  typedef CleanResult_<ContainerAllocator> Type;

  CleanResult_()
    : status()  {
    }
  CleanResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::ocrtoc_task::CleanResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ocrtoc_task::CleanResult_<ContainerAllocator> const> ConstPtr;

}; // struct CleanResult_

typedef ::ocrtoc_task::CleanResult_<std::allocator<void> > CleanResult;

typedef boost::shared_ptr< ::ocrtoc_task::CleanResult > CleanResultPtr;
typedef boost::shared_ptr< ::ocrtoc_task::CleanResult const> CleanResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ocrtoc_task::CleanResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ocrtoc_task::CleanResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ocrtoc_task::CleanResult_<ContainerAllocator1> & lhs, const ::ocrtoc_task::CleanResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ocrtoc_task::CleanResult_<ContainerAllocator1> & lhs, const ::ocrtoc_task::CleanResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ocrtoc_task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ocrtoc_task::CleanResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ocrtoc_task::CleanResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocrtoc_task::CleanResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::ocrtoc_task::CleanResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ocrtoc_task/CleanResult";
  }

  static const char* value(const ::ocrtoc_task::CleanResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"string status\n"
;
  }

  static const char* value(const ::ocrtoc_task::CleanResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CleanResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ocrtoc_task::CleanResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ocrtoc_task::CleanResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCRTOC_TASK_MESSAGE_CLEANRESULT_H
