// Generated by gencpp from file haf_grasping/ShowOnlyBestGraspRequest.msg
// DO NOT EDIT!


#ifndef HAF_GRASPING_MESSAGE_SHOWONLYBESTGRASPREQUEST_H
#define HAF_GRASPING_MESSAGE_SHOWONLYBESTGRASPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haf_grasping
{
template <class ContainerAllocator>
struct ShowOnlyBestGraspRequest_
{
  typedef ShowOnlyBestGraspRequest_<ContainerAllocator> Type;

  ShowOnlyBestGraspRequest_()
    : show_only_best_grasp(false)  {
    }
  ShowOnlyBestGraspRequest_(const ContainerAllocator& _alloc)
    : show_only_best_grasp(false)  {
  (void)_alloc;
    }



   typedef uint8_t _show_only_best_grasp_type;
  _show_only_best_grasp_type show_only_best_grasp;





  typedef boost::shared_ptr< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShowOnlyBestGraspRequest_

typedef ::haf_grasping::ShowOnlyBestGraspRequest_<std::allocator<void> > ShowOnlyBestGraspRequest;

typedef boost::shared_ptr< ::haf_grasping::ShowOnlyBestGraspRequest > ShowOnlyBestGraspRequestPtr;
typedef boost::shared_ptr< ::haf_grasping::ShowOnlyBestGraspRequest const> ShowOnlyBestGraspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator1> & lhs, const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator2> & rhs)
{
  return lhs.show_only_best_grasp == rhs.show_only_best_grasp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator1> & lhs, const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace haf_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2884e314840573d98e3fd64b18c919d8";
  }

  static const char* value(const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2884e314840573d9ULL;
  static const uint64_t static_value2 = 0x8e3fd64b18c919d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haf_grasping/ShowOnlyBestGraspRequest";
  }

  static const char* value(const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool show_only_best_grasp			# ShowOnlyBestGrasp: defines if only the best grasp should be visualized\n"
;
  }

  static const char* value(const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.show_only_best_grasp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShowOnlyBestGraspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haf_grasping::ShowOnlyBestGraspRequest_<ContainerAllocator>& v)
  {
    s << indent << "show_only_best_grasp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.show_only_best_grasp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAF_GRASPING_MESSAGE_SHOWONLYBESTGRASPREQUEST_H
