// Generated by gencpp from file ocrtoc_task/CleanFeedback.msg
// DO NOT EDIT!


#ifndef OCRTOC_TASK_MESSAGE_CLEANFEEDBACK_H
#define OCRTOC_TASK_MESSAGE_CLEANFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ocrtoc_task
{
template <class ContainerAllocator>
struct CleanFeedback_
{
  typedef CleanFeedback_<ContainerAllocator> Type;

  CleanFeedback_()
    : text()  {
    }
  CleanFeedback_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CleanFeedback_

typedef ::ocrtoc_task::CleanFeedback_<std::allocator<void> > CleanFeedback;

typedef boost::shared_ptr< ::ocrtoc_task::CleanFeedback > CleanFeedbackPtr;
typedef boost::shared_ptr< ::ocrtoc_task::CleanFeedback const> CleanFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ocrtoc_task::CleanFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ocrtoc_task::CleanFeedback_<ContainerAllocator1> & lhs, const ::ocrtoc_task::CleanFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ocrtoc_task::CleanFeedback_<ContainerAllocator1> & lhs, const ::ocrtoc_task::CleanFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ocrtoc_task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::ocrtoc_task::CleanFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ocrtoc_task/CleanFeedback";
  }

  static const char* value(const ::ocrtoc_task::CleanFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"string text\n"
"\n"
;
  }

  static const char* value(const ::ocrtoc_task::CleanFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CleanFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ocrtoc_task::CleanFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ocrtoc_task::CleanFeedback_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCRTOC_TASK_MESSAGE_CLEANFEEDBACK_H
