controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
  - name: fake_gripper_controller
    joints:
      - claw_1b_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: init_pose
  - group: gripper
    pose: gripper_open