# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_controller
  joint_model_group_pose: init_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - ur5_l_finger_joint
    - ur5_l_finger_pad_joint
    - ur5_r_finger_joint
    - ur5_r_finger_pad_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
#  - name: gripper_controller
#    action_ns: follow_joint_trajectory
#    default: True
#    type: FollowJointTrajectory
#    joints:
#      - ur5_l_finger_joint
#      - ur5_r_finger_joint
  - name: gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: True
    parallel: True
    joints:
      - ur5_l_finger_joint
      - ur5_r_finger_joint
