// Generated by gencpp from file haf_grasping/GraspPreGripperOpeningWidthRequest.msg
// DO NOT EDIT!


#ifndef HAF_GRASPING_MESSAGE_GRASPPREGRIPPEROPENINGWIDTHREQUEST_H
#define HAF_GRASPING_MESSAGE_GRASPPREGRIPPEROPENINGWIDTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haf_grasping
{
template <class ContainerAllocator>
struct GraspPreGripperOpeningWidthRequest_
{
  typedef GraspPreGripperOpeningWidthRequest_<ContainerAllocator> Type;

  GraspPreGripperOpeningWidthRequest_()
    : gripper_opening_width(0)  {
    }
  GraspPreGripperOpeningWidthRequest_(const ContainerAllocator& _alloc)
    : gripper_opening_width(0)  {
  (void)_alloc;
    }



   typedef int32_t _gripper_opening_width_type;
  _gripper_opening_width_type gripper_opening_width;





  typedef boost::shared_ptr< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspPreGripperOpeningWidthRequest_

typedef ::haf_grasping::GraspPreGripperOpeningWidthRequest_<std::allocator<void> > GraspPreGripperOpeningWidthRequest;

typedef boost::shared_ptr< ::haf_grasping::GraspPreGripperOpeningWidthRequest > GraspPreGripperOpeningWidthRequestPtr;
typedef boost::shared_ptr< ::haf_grasping::GraspPreGripperOpeningWidthRequest const> GraspPreGripperOpeningWidthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator1> & lhs, const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gripper_opening_width == rhs.gripper_opening_width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator1> & lhs, const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace haf_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0f2ffb7339463e86d9c2a177592739e";
  }

  static const char* value(const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0f2ffb7339463e8ULL;
  static const uint64_t static_value2 = 0x6d9c2a177592739eULL;
};

template<class ContainerAllocator>
struct DataType< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haf_grasping/GraspPreGripperOpeningWidthRequest";
  }

  static const char* value(const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 gripper_opening_width			# factor f that is used for scaling point cloud to imitate pre-gripper opening width of 1/f\n"
;
  }

  static const char* value(const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_opening_width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspPreGripperOpeningWidthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haf_grasping::GraspPreGripperOpeningWidthRequest_<ContainerAllocator>& v)
  {
    s << indent << "gripper_opening_width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gripper_opening_width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAF_GRASPING_MESSAGE_GRASPPREGRIPPEROPENINGWIDTHREQUEST_H
